### PR TITLE
Add portuguese dates

### PR DESCRIPTION
**Pull request by isaccavalcante**

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Should be removed i18n related files because they have already been merged into master.

**Comment by g1eny0ung** [comment]
And should also update the `summary.html` to make it take effect.

Example:

https://github.com/g1eny0ung/hugo-theme-dream/blob/9e75311d8c1b83dd9f1d5d2e72879755e93e4b5b/layouts/_default/summary.html#L18

**Comment by isaccavalcante** [comment]
Done!

**Comment by g1eny0ung** [comment]
Already merged.~

**Pull request merged**
