### PR TITLE
Add more languages (needs checking)

### PR DESCRIPTION
**Pull request by Darthagnon**
Arabic (RTL, probable bugs/incorrect translations), Hebrew (RTL, similar), Catalan, German (data), Japanese (data), Latvian, Romanian, Russian, Slovenian

### High-confidence:
Minor additions of missing languages already in ```i18n``` to ```data``` folder, or Latin languages which I can understand enough to get a good Google translate
- Catalan
- German
- Japanese
- Romanian
### Medium confidence
I don't speak or understand these languages; used Google translate. Should be okay, though.
- Latvian
- Russian
- Slovenian
### Low confidence
(I don't speak these at all, and they're right-to-left, so probably buggy?)
- Arabic
- Hebrew

### CODE REVIEW

**Comment by Darthagnon** [comment]
Wondering, why are days of the week numbered 0-6, not 1-7? e.g. in Portuguese, my language, Monday = 2 = Segunda-feira = "second day", etc.

**Comment by g1eny0ung** [comment]
> Wondering, why are days of the week numbered 0-6 in `data`, not 1-7? e.g. in Portuguese, my language, Monday = 2 = Segunda-feira = "second day", etc.

First thx for the contributions! 🍾 I think all of these can be merged even though some languages haven't enough checking. Because I think these can encourage more people to use them and find out something unreasonable.

As for why 0 is used as the start because programming generally uses 0 as the start of the index.

**Comment by g1eny0ung** [comment]
💯 I will merge this PR right now. Feel free to comment if there still have any problems.

**Comment by Darthagnon** [comment]
Thank you for merging! I hope to be able to contribute more in the near future, as I want to use this theme on my blog :D

**Pull request merged**
