### PR TITLE
refactor: supplement meta tags for SEO

### LINKED ISSUE #304: Enhancement Proposal for SEO Improvement - Adding Keywords Support
Hello, i hope this message finds you well. Firstly, i want to commend you on the exceptional work you've done with the hugo-theme-dream. 

Proposal:
I've noticed that the theme has strong SEO features, which is great for improving search engine visibility. However, I believe that incorporating support for keywords further enhance the theme's SEO capabilities. Keywords are crucial for search engine optimization and could help improve the theme's effectiveness in targeting specific search queries.
Would it be possible to consider adding a feature or option to include keywords in the theme's meta tags?

If you're open to this idea, I'd be happy to provide further details or collaborate on how this feature could be integrated into the theme.
Thank you for considering this enhancement. I look forward to your thoughts and i'm eager to contribute to making the hugo-theme-dream even better. 

Best regards,
MaximoVolynets

### PR DESCRIPTION
**Pull request by g1eny0ung**
Close #304.

For more information, please refer to the related issue.

### CODE REVIEW

**Comment by MaximoVolynets** [comment]
Thank you so much for your prompt response and for considering the addition of keywords support. I appreciate your efforts to enhance the theme. I'll hold off on testing until the PR is merged to ensure i'm working with the finalized changes. I'm happy to contribute in any way that might be helpful. Looking forward to seeing the update in action!
Regards

**Comment by g1eny0ung** [comment]
> Thank you so much for your prompt response and for considering the addition of keywords support. I appreciate your efforts to enhance the theme. I'll hold off on testing until the PR is merged to ensure i'm working with the finalized changes. I'm happy to contribute in any way that might be helpful. Looking forward to seeing the update in action! Regards

I've tested it at my local so I can merge it now. If you still have questions, feel free to open a new issue. 😃

**Comment by MaximoVolynets** [comment]
Thank you! Wish you all the best.

**Comment by g1eny0ung** [comment]
@MaximoVolynets I've updated it again. Because I found that I misused the `_internal/schema.html`, please update the latest code and then test.

**Comment by MaximoVolynets** [comment]
Thank you! Later I’ll test and give you updates.

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Yue Yang ***@***.***>
Enviado: Saturday, August 24, 2024 3:45:25 PM
Para: g1eny0ung/hugo-theme-dream ***@***.***>
Cc: MaximoVolynets ***@***.***>; Mention ***@***.***>
Assunto: Re: [g1eny0ung/hugo-theme-dream] refactor: supplement meta tags for SEO (PR #305)


@MaximoVolynets<https://github.com/MaximoVolynets> I've updated it again. Because I found that I misused the _internal/schema.html, please update the latest code and then test.

**Pull request merged**
