### PR TITLE
Added gallery shortcut using hugo-easy-gallery

### PR DESCRIPTION
**Pull request by haogis**
ref: https://github.com/liwenyip/hugo-easy-gallery/

basically added all the .html files and .css and .js file based on what liwenyip described in hugo-easy-gallery.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Why should this theme need this feature?

**Comment by haogis** [comment]
> Why should this theme need this feature?

Sorry Young I forgot to describe the issue. This is a requirement from idolstation again. There are times that there are multiple images appear in one post. By adding this shortcut function, it allows the images to be aggregated and make pages look more neat. And users can look at the images closely which sounds important when looking at an idol.

**Comment by g1eny0ung** [comment]
Know about it. You can create a folder named `layouts` in your source root and pass all `shortcodes` into it. It doesn't need to bound to the theme.

Ref: https://gohugo.io/templates/lookup-order/.

**Comment by haogis** [comment]
> Know about it. You can create a folder named `layouts` in your source root and pass all `shortcodes` into it. It doesn't need to bound to the theme.
> 
> Ref: https://gohugo.io/templates/lookup-order/.

Ohhh. Okay. Didn’t know that. All right I will close this PR and implement it on our side. Thanks!

**Pull request closed without merging**
